---
kind: pipeline
name: analysis

platform:
  os: linux
  arch: arm64

steps:
- name: code-analysis
  image: aosapps/drone-sonar-plugin
  settings:
    sonar_host:
      from_secret: sonar_host
    sonar_token:
      from_secret: sonar_token
  when:
    branch:
      include:
      - master
      - feature/*
      
+   ver: 1.0
+   timeout: 20
+   sources: .
+   level: DEBUG
+   showProfiling: true
---
kind: pipeline
name: python-3

steps:
- name: test
  image: python:3.7
  commands:
  - pip install pipreqs
  - pipreqs .
  - pip install -r requirements.txt
  - python -m unittest discover -s . -p "*_test.py"
