---
kind: pipeline
name: analysis

steps:
- name: code-analysis
  image: aosapps/drone-sonar-plugin
  settings:
    sonar_host:
      from_secret: sonar_host
    sonar_token:
      from_secret: sonar_token      
+   level: TRACE
+   showProfiling: true
  commands:
  - sonar-scanner \
    -Dsonar.projectKey=handy \
    -Dsonar.sources=. \
    -Dsonar.host.url=http://sonarqube.deepmatter.me \
    -Dsonar.login=3066687518dd6c7f687749d38013b6efde518751
---
kind: pipeline
name: python-3

steps:
- name: test
  image: python:3.7
  commands:
  - pip install pipreqs
  - pipreqs .
  - pip install -r requirements.txt
  - python -m unittest discover -s . -p "*_test.py"
