---
kind: pipeline
name: analysis

steps:
- name: code-analysis
  image: aosapps/drone-sonar-plugin
  settings:
    sonar_host:
      from_secret: sonar_host
    sonar_token:
      from_secret: sonar_token
  commands:
      - sonar-scanner -Dsonar.projectKey=${DRONE_REPO}
        -Dsonar.projectName=${DRONE_REPO}
        -Dsonar.host.url=${sonar_host}
        -Dsonar.login=${sonar_token}
        -Dsonar.sources=.
+   ver: 0.0.1
+   timeout: 120
+   level: TRACE
+   showProfiling: true
---
kind: pipeline
name: python-3

steps:
- name: test
  image: python:3.7
  commands:
  - pip install pipreqs
  - pipreqs .
  - pip install -r requirements.txt
  - python -m unittest discover -s . -p "*_test.py"
